### ISSUE TITLE
Update `/version` endpoint to use actual version

### ISSUE THREAD

**Issue by MiloszKrajewski** [MiloszKrajewski/TooMany#18]

**Comment by jonathonhawkins92** [comment]
I will add the current version to the Nav.

**Comment by jonathonhawkins92** [comment]
Done in the vite branch, though it seems to be hard coded to `0.0.0`.

**Comment by MiloszKrajewski** [comment]
Yes, it is ;-)
![image](https://user-images.githubusercontent.com/4333436/114322317-58205880-9b17-11eb-9e88-f13a33da4225.png)

**Comment by MiloszKrajewski** [comment]
done
