### ISSUE TITLE
Home/About Page

### ISSUE THREAD

**Issue by MiloszKrajewski** [MiloszKrajewski/TooMany#19]

**Comment by jonathonhawkins92** [comment]
I've added a landing page inspired by VSCode's welcome page, this can also contain the about text.

**Comment by jonathonhawkins92** [comment]
@MiloszKrajewski could you outline what you want the about menu to contain?

**Comment by jonathonhawkins92** [comment]
Spoke about on a call, things the welcome/about page should contain:

 - About text
 - Create new button
 - Version numbers
 - List developers
 - List libraries that are in use
 - Licence info
 
 @MiloszKrajewski to add to this thread a list of libraries and the licence info, I will add the rest for review.

**Comment by jonathonhawkins92** [comment]
@MiloszKrajewski I've done all but the API dependencies.

![image](https://user-images.githubusercontent.com/22887074/117193434-c1278300-adda-11eb-83c6-c2837afde628.png)

**Comment by MiloszKrajewski** [comment]
Nice!
